drop table if exists member CASCADE;
create table member
(
id bigint generated by default as identity, --id값을 넣지 않아도 자동으로 채워준다
name varchar(255),
primary key (id)
);

insert into member(name) values("spring")
insert into member(name) values("spring2")